<div class="row">


    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-purple">
            <div class="inner">
                <h3>Home<sup style="font-size: 20px"></sup></h3>
                <p></p>
                <p>Analysis of Life Expectancy</p>
            </div>
            <div class="icon">
                <i><img src="<?php echo $assets_url; ?>img/population.png" /> </i>
            </div>
            <a href="<?php echo $base_url; ?>" class="small-box-footer">View Analysis <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->

    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>Sanitation<sup style="font-size: 20px"></sup></h3>
                <p></p>
                <p> Sanitation Analysis</p>
            </div>
            <div class="icon">
                <i><img src="<?php echo $assets_url; ?>img/sanitation.png" /> </i>
            </div>
            <a href="<?php echo $cont_url; ?>sanitation" class="small-box-footer"> View Analysis <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-teal-active">
            <div class="inner">
                <h3>Physicians<sup style="font-size: 20px"></sup></h3>
                <p></p>
                <p>Health Workers Analysis</p>
            </div>
            <div class="icon">
                <i><img src="<?php echo $assets_url; ?>img/doctor.png" /> </i>
            </div>
            <a href="<?php echo $cont_url; ?>physicians" class="small-box-footer"> View Analysis <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->

    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>Diseases<sup style="font-size: 20px"></sup></h3>
                <p></p>
                <p> Common Diseases Analysis</p>
            </div>
            <div class="icon">
                <i><img src="<?php echo $assets_url; ?>img/diseases.png" /> </i>
            </div>
            <a href="<?php echo $cont_url; ?>diseases" class="small-box-footer"> View Analysis <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->


</div><!-- /.row -->